/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.scaler.java.testdemo;

public class App {

    public static void main(String[] args) {
        System.out.println("Hello!");
    }
}
